# finbank/deployments/k8s/fraud-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
      - name: fraud-service
        image: fraud-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  selector:
    app: fraud-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
